### ISSUE TITLE
Completed module 2 assignments

### ISSUE THREAD

**Issue by nrdiwita** [ds4owd-001/md-02-assignments-nrdiwita#1]
@larnsce @mianzg @sskorik01
How do you delete code chunks? I made some mistakes when I tried to fix the code chunk indentations and now I'm left with empty code chunks in my R script.
Also, I missed the first few parts of last week's lecture, particularly when you explain commit, push, pull, etc. I tried reviewing the lecture slides but couldn't really make sense of it. Is there any way you can provide additional explanation?

Thank you!

**Comment by sskorik01** [comment]
Hi,

I don't think there is an in-built function to delete code chunks. What I do is that I switch to source mode, I delete the code that creates a code chunk and then switch back to visual mode. The code chunk will have disappeared. 
`

![Image](https://github.com/ds4owd-001/md-02-assignments-nrdiwita/assets/148224762/f78d97d2-3e75-4dad-8c95-155befb0c836)
![Image](https://github.com/ds4owd-001/md-02-assignments-nrdiwita/assets/148224762/98743c3c-6b0d-4d58-8033-b3daf2beb49a)

`

Concerning GitHub commands, did you manage to commit and push your code already? Here is a general explanation about git and the main commands.

Git is a version control system that allows developers to track changes to their code over time. It provides several commands to manage the code repository, including commit, push, and pull.

**Commit:** A commit is a snapshot of the code at a specific point in time. It records changes to the repository and saves them in the local repository. When you commit changes, you are creating a new version of the code that can be tracked and reverted if necessary. 

**Push:** Pushing is the process of sending the recent commit history from your local repository (your posit.cloud) up to a remote repository, such as GitHub. It updates the remote repository with the changes you have made locally. 

**Pull:** Pulling is the process of retrieving changes from the remote repository (GitHub) and merging them into your local repository (Posit.cloud). It is used to update your local repository with changes made by others. 

Let me know if there is something in particular you don't understand!
